spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${MYSQL_PORT:3306}/plamingo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:20}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT_MS:3000}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 3s

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    prometheus:
      access: none
    metrics:
      access: none
